"""add ext_password_encrypted field in users table

Revision ID: cc363acb599f
Revises: 836e5d94e2ee
Create Date: 2025-12-15 20:32:39.017284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc363acb599f'
down_revision: Union[str, Sequence[str], None] = '836e5d94e2ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ext_password_encrypted', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ext_password_encrypted')
    # ### end Alembic commands ###
